-- GENERATED by tools/ci/emit-schema.ts — do not edit by hand.
-- Source of truth: packages/schema/src/tables/*.ts and packages/contracts/src/terms.ts
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS currencies (
  code text NOT NULL,
  minor_units integer NOT NULL,
  PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS part_manufacturers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (version)
);

CREATE TABLE IF NOT EXISTS term_registry (
  key text NOT NULL,
  authoring_tiers jsonb NOT NULL,
  combine_kind text NOT NULL CHECK (combine_kind IN ('nearest','ratchet','attach')),
  stricter text CHECK (stricter IN ('lower','higher')),
  value_kind text NOT NULL,
  enum_values jsonb,
  PRIMARY KEY (key)
);

-- Tenant roots. PROSPECT is a real row here, which is why pre-account leads need no nullable column.
CREATE TABLE IF NOT EXISTS organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('internal','customer','subcontractor','vendor','prospect')),
  external_ref text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

-- The shard boundary itself.
CREATE TABLE IF NOT EXISTS regions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  timezone text NOT NULL DEFAULT 'America/Chicago',
  min_crew_density integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  parent_id uuid REFERENCES accounts(id),
  tier text NOT NULL CHECK (tier IN ('region','location','site')),
  name text NOT NULL,
  customer_group text,
  external_ref text,
  address jsonb,
  timezone text,
  active boolean NOT NULL DEFAULT true,
  path uuid[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  CONSTRAINT accounts_region_has_no_parent CHECK ((tier = 'region') = (parent_id IS NULL))
);
CREATE INDEX IF NOT EXISTS accounts_region_id_idx ON accounts (region_id);
CREATE INDEX IF NOT EXISTS accounts_parent_id_idx ON accounts (parent_id);
CREATE INDEX IF NOT EXISTS accounts_tier_idx ON accounts (tier);
CREATE INDEX IF NOT EXISTS accounts_org_id_tier_idx ON accounts (org_id, tier);
CREATE INDEX IF NOT EXISTS accounts_customer_group_idx ON accounts (customer_group);

CREATE TABLE IF NOT EXISTS equipment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  site_id uuid NOT NULL REFERENCES accounts(id),
  manufacturer_id uuid REFERENCES part_manufacturers(id),
  model text NOT NULL,
  serial text,
  installed_on date,
  tonnage_milli integer,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS equipment_region_id_idx ON equipment (region_id);
CREATE INDEX IF NOT EXISTS equipment_site_id_idx ON equipment (site_id);
CREATE INDEX IF NOT EXISTS equipment_serial_idx ON equipment (serial);

CREATE TABLE IF NOT EXISTS subcontractor_firms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  legal_name text NOT NULL,
  status text NOT NULL CHECK (status IN ('onboarding','active','suspended','terminated')),
  settlement_terms_days integer NOT NULL,
  msa_signed_at timestamptz,
  diagnostic_data_rights_reserved boolean NOT NULL,
  w9_document_key text,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS subcontractor_firms_region_id_idx ON subcontractor_firms (region_id);

CREATE TABLE IF NOT EXISTS crews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  label text NOT NULL,
  employment_type text NOT NULL CHECK (employment_type IN ('employed','subcontracted')),
  firm_id uuid REFERENCES subcontractor_firms(id),
  home_region_id uuid NOT NULL REFERENCES regions(id),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  CONSTRAINT crews_subcontracted_have_firm CHECK ((employment_type = 'subcontracted') = (firm_id IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS crews_region_id_idx ON crews (region_id);
CREATE INDEX IF NOT EXISTS crews_firm_id_idx ON crews (firm_id);
CREATE INDEX IF NOT EXISTS crews_home_region_id_idx ON crews (home_region_id);

CREATE TABLE IF NOT EXISTS crew_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  crew_id uuid NOT NULL REFERENCES crews(id),
  kind text NOT NULL CHECK (kind IN ('insurance','license','certification','background_check')),
  identifier text NOT NULL,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  document_key text,
  verified_at timestamptz,
  verified_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS crew_credentials_region_id_idx ON crew_credentials (region_id);
CREATE INDEX IF NOT EXISTS crew_credentials_crew_id_valid_to_idx ON crew_credentials (crew_id, valid_to);
CREATE INDEX IF NOT EXISTS crew_credentials_valid_to_idx ON crew_credentials (valid_to);

CREATE TABLE IF NOT EXISTS rate_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  firm_id uuid NOT NULL REFERENCES subcontractor_firms(id),
  service_code text NOT NULL,
  rate_minor bigint NOT NULL,
  currency text NOT NULL REFERENCES currencies(code),
  effective daterange NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  CONSTRAINT rate_cards_no_overlap EXCLUDE USING gist (firm_id WITH =, service_code WITH =, effective WITH &&)
);
CREATE INDEX IF NOT EXISTS rate_cards_region_id_idx ON rate_cards (region_id);
CREATE INDEX IF NOT EXISTS rate_cards_firm_id_service_code_idx ON rate_cards (firm_id, service_code);

CREATE TABLE IF NOT EXISTS users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  namespace text NOT NULL CHECK (namespace IN ('internal','customer','subcontractor','vendor')),
  email text NOT NULL,
  display_name text NOT NULL,
  roles jsonb NOT NULL DEFAULT '[]'::jsonb,
  scope_tier text NOT NULL CHECK (scope_tier IN ('parent','region','location','site')),
  scope_id uuid NOT NULL,
  firm_id uuid REFERENCES subcontractor_firms(id),
  crew_id uuid REFERENCES crews(id),
  external_idp_subject text,
  password_hash text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (email),
  CONSTRAINT users_subcontractor_have_firm CHECK ((namespace = 'subcontractor') = (firm_id IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS users_region_id_idx ON users (region_id);
CREATE INDEX IF NOT EXISTS users_namespace_email_idx ON users (namespace, email);
CREATE INDEX IF NOT EXISTS users_firm_id_idx ON users (firm_id);
CREATE INDEX IF NOT EXISTS users_scope_tier_scope_id_idx ON users (scope_tier, scope_id);

CREATE TABLE IF NOT EXISTS devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  hardware_id text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('android_pilot','yocto_tablet','web_fallback')),
  public_key bytea NOT NULL,
  firm_id uuid REFERENCES subcontractor_firms(id),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (hardware_id)
);
CREATE INDEX IF NOT EXISTS devices_region_id_idx ON devices (region_id);
CREATE INDEX IF NOT EXISTS devices_hardware_id_idx ON devices (hardware_id);

CREATE TABLE IF NOT EXISTS device_grants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  device_id uuid NOT NULL REFERENCES devices(id),
  crew_id uuid NOT NULL REFERENCES crews(id),
  technician_id uuid NOT NULL REFERENCES users(id),
  service_window tstzrange NOT NULL,
  granted_by uuid NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS device_grants_region_id_idx ON device_grants (region_id);
CREATE INDEX IF NOT EXISTS device_grants_device_id_idx ON device_grants (device_id);
CREATE INDEX IF NOT EXISTS device_grants_crew_id_idx ON device_grants (crew_id);

CREATE TABLE IF NOT EXISTS sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  principal_kind text NOT NULL CHECK (principal_kind IN ('user','device_grant','anonymous')),
  principal_id uuid NOT NULL,
  issued_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  surface_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS sessions_region_id_idx ON sessions (region_id);
CREATE INDEX IF NOT EXISTS sessions_principal_id_idx ON sessions (principal_id);
CREATE INDEX IF NOT EXISTS sessions_expires_at_idx ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  scope_tier text NOT NULL CHECK (scope_tier IN ('parent','region','location','site')),
  scope_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind IN ('msa','amendment','location_agreement','project_sow','residential_membership','one_time')),
  parent_contract_id uuid REFERENCES contracts(id),
  billing_path text NOT NULL CHECK (billing_path IN ('one_time','residential_membership','enterprise_sla','project')),
  signed_at timestamptz NOT NULL,
  effective daterange NOT NULL,
  diagnostic_data_rights_reserved boolean NOT NULL,
  document_key text,
  state text NOT NULL DEFAULT 'draft' CHECK (state IN ('draft','active','expired','terminated')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS contracts_region_id_idx ON contracts (region_id);
CREATE INDEX IF NOT EXISTS contracts_scope_tier_scope_id_idx ON contracts (scope_tier, scope_id);
CREATE INDEX IF NOT EXISTS contracts_parent_contract_id_idx ON contracts (parent_contract_id);

CREATE TABLE IF NOT EXISTS contract_term_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  contract_id uuid NOT NULL REFERENCES contracts(id),
  scope_tier text NOT NULL CHECK (scope_tier IN ('parent','region','location','site')),
  scope_id uuid NOT NULL,
  term_key text NOT NULL REFERENCES term_registry(key),
  term_value jsonb NOT NULL,
  effective daterange NOT NULL,
  authored_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  CONSTRAINT term_override_no_overlap EXCLUDE USING gist (scope_tier WITH =, scope_id WITH =, term_key WITH =, effective WITH &&)
);
CREATE INDEX IF NOT EXISTS contract_term_overrides_region_id_idx ON contract_term_overrides (region_id);
CREATE INDEX IF NOT EXISTS contract_term_overrides_scope_tier_scope_id_term_key_idx ON contract_term_overrides (scope_tier, scope_id, term_key);
CREATE INDEX IF NOT EXISTS contract_term_overrides_contract_id_idx ON contract_term_overrides (contract_id);

CREATE TABLE IF NOT EXISTS leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  source text NOT NULL,
  contact jsonb NOT NULL,
  requested_metro text,
  converted_account_id uuid REFERENCES accounts(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS leads_region_id_idx ON leads (region_id);
CREATE INDEX IF NOT EXISTS leads_converted_account_id_idx ON leads (converted_account_id);

CREATE TABLE IF NOT EXISTS call_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  lead_id uuid REFERENCES leads(id),
  direction text NOT NULL CHECK (direction IN ('inbound','outbound')),
  recording_key text,
  occurred_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS call_records_region_id_idx ON call_records (region_id);
CREATE INDEX IF NOT EXISTS call_records_lead_id_idx ON call_records (lead_id);

CREATE TABLE IF NOT EXISTS projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  contract_id uuid NOT NULL REFERENCES contracts(id),
  name text NOT NULL,
  foreman_id uuid REFERENCES users(id),
  service_window tstzrange NOT NULL,
  state text NOT NULL DEFAULT 'planned' CHECK (state IN ('planned','active','closed','cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS projects_region_id_idx ON projects (region_id);
CREATE INDEX IF NOT EXISTS projects_contract_id_idx ON projects (contract_id);
CREATE INDEX IF NOT EXISTS projects_foreman_id_idx ON projects (foreman_id);

CREATE TABLE IF NOT EXISTS jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  site_id uuid NOT NULL REFERENCES accounts(id),
  contract_id uuid REFERENCES contracts(id),
  project_id uuid REFERENCES projects(id),
  service_code text NOT NULL,
  priority text NOT NULL DEFAULT 'routine' CHECK (priority IN ('emergency','urgent','routine','pm')),
  service_window tstzrange NOT NULL,
  state text NOT NULL DEFAULT 'created' CHECK (state IN ('created','assigned','en_route','on_site','in_progress','awaiting_parts','complete','reopened','invoiced','cancelled','aborted')),
  version integer NOT NULL DEFAULT 1,
  opened_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS jobs_region_id_idx ON jobs (region_id);
CREATE INDEX IF NOT EXISTS jobs_site_id_idx ON jobs (site_id);
CREATE INDEX IF NOT EXISTS jobs_state_idx ON jobs (state);
CREATE INDEX IF NOT EXISTS jobs_project_id_idx ON jobs (project_id);
CREATE INDEX IF NOT EXISTS jobs_contract_id_idx ON jobs (contract_id);

CREATE TABLE IF NOT EXISTS compliance_clearances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  crew_id uuid NOT NULL REFERENCES crews(id),
  service_window tstzrange NOT NULL,
  credential_ids jsonb NOT NULL,
  evaluated_at timestamptz NOT NULL,
  evaluated_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS compliance_clearances_region_id_idx ON compliance_clearances (region_id);
CREATE INDEX IF NOT EXISTS compliance_clearances_crew_id_idx ON compliance_clearances (crew_id);

CREATE TABLE IF NOT EXISTS assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  crew_id uuid NOT NULL REFERENCES crews(id),
  clearance_id uuid NOT NULL REFERENCES compliance_clearances(id),
  assigned_by uuid NOT NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  released_at timestamptz,
  release_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS assignments_region_id_idx ON assignments (region_id);
CREATE INDEX IF NOT EXISTS assignments_job_id_idx ON assignments (job_id);
CREATE INDEX IF NOT EXISTS assignments_crew_id_idx ON assignments (crew_id);

CREATE TABLE IF NOT EXISTS job_state_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  from_state text,
  to_state text NOT NULL,
  actor_id uuid NOT NULL,
  surface_id text NOT NULL,
  mutation_id text NOT NULL,
  occurred_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (job_id, mutation_id)
);
CREATE INDEX IF NOT EXISTS job_state_events_region_id_idx ON job_state_events (region_id);
CREATE INDEX IF NOT EXISTS job_state_events_job_id_occurred_at_idx ON job_state_events (job_id, occurred_at);

CREATE TABLE IF NOT EXISTS job_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  storage_key text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('photo','diagnostic_capture','signature','document')),
  captured_at timestamptz NOT NULL,
  captured_by uuid NOT NULL,
  mutation_id text NOT NULL,
  meta jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (job_id, mutation_id)
);
CREATE INDEX IF NOT EXISTS job_media_region_id_idx ON job_media (region_id);
CREATE INDEX IF NOT EXISTS job_media_job_id_idx ON job_media (job_id);

CREATE TABLE IF NOT EXISTS time_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  crew_id uuid NOT NULL REFERENCES crews(id),
  span tstzrange NOT NULL,
  kind text NOT NULL CHECK (kind IN ('travel','labor','wait')),
  mutation_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (job_id, mutation_id)
);
CREATE INDEX IF NOT EXISTS time_entries_region_id_idx ON time_entries (region_id);
CREATE INDEX IF NOT EXISTS time_entries_job_id_idx ON time_entries (job_id);
CREATE INDEX IF NOT EXISTS time_entries_crew_id_idx ON time_entries (crew_id);

CREATE TABLE IF NOT EXISTS checklist_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  item_key text NOT NULL,
  response jsonb NOT NULL,
  answered_at timestamptz NOT NULL,
  answered_by uuid NOT NULL,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (job_id, item_key)
);
CREATE INDEX IF NOT EXISTS checklist_items_region_id_idx ON checklist_items (region_id);
CREATE INDEX IF NOT EXISTS checklist_items_job_id_idx ON checklist_items (job_id);

CREATE TABLE IF NOT EXISTS parts_used (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  part_sku text NOT NULL,
  quantity_milli bigint NOT NULL,
  source text NOT NULL CHECK (source IN ('truck','location_stock','regional_hub','national')),
  mutation_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (job_id, mutation_id)
);
CREATE INDEX IF NOT EXISTS parts_used_region_id_idx ON parts_used (region_id);
CREATE INDEX IF NOT EXISTS parts_used_job_id_idx ON parts_used (job_id);

CREATE TABLE IF NOT EXISTS warranty_cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  equipment_id uuid REFERENCES equipment(id),
  claimed_minor bigint NOT NULL,
  currency text NOT NULL REFERENCES currencies(code),
  state text NOT NULL DEFAULT 'open' CHECK (state IN ('open','approved','denied','escalated')),
  decided_by uuid,
  decided_at timestamptz,
  decision_note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS warranty_cases_region_id_idx ON warranty_cases (region_id);
CREATE INDEX IF NOT EXISTS warranty_cases_job_id_idx ON warranty_cases (job_id);
CREATE INDEX IF NOT EXISTS warranty_cases_state_idx ON warranty_cases (state);

CREATE TABLE IF NOT EXISTS service_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  site_id uuid NOT NULL REFERENCES accounts(id),
  requested_by uuid NOT NULL,
  priority text NOT NULL DEFAULT 'routine' CHECK (priority IN ('emergency','urgent','routine')),
  description text NOT NULL,
  job_id uuid REFERENCES jobs(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS service_requests_region_id_idx ON service_requests (region_id);
CREATE INDEX IF NOT EXISTS service_requests_site_id_idx ON service_requests (site_id);

CREATE TABLE IF NOT EXISTS invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  bill_to_tier text NOT NULL CHECK (bill_to_tier IN ('parent','region','location','site')),
  bill_to_id uuid NOT NULL,
  contract_id uuid NOT NULL REFERENCES contracts(id),
  billing_path text NOT NULL CHECK (billing_path IN ('one_time','residential_membership','enterprise_sla','project')),
  period_start date,
  period_end date,
  total_minor bigint NOT NULL,
  currency text NOT NULL REFERENCES currencies(code),
  issued_at timestamptz,
  due_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS invoices_region_id_idx ON invoices (region_id);
CREATE INDEX IF NOT EXISTS invoices_bill_to_tier_bill_to_id_idx ON invoices (bill_to_tier, bill_to_id);
CREATE INDEX IF NOT EXISTS invoices_contract_id_idx ON invoices (contract_id);

CREATE TABLE IF NOT EXISTS invoice_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  invoice_id uuid NOT NULL REFERENCES invoices(id),
  location_id uuid NOT NULL REFERENCES accounts(id),
  customer_group text,
  job_id uuid REFERENCES jobs(id),
  description text NOT NULL,
  quantity_milli bigint NOT NULL,
  unit_price_minor bigint NOT NULL,
  amount_minor bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS invoice_lines_region_id_idx ON invoice_lines (region_id);
CREATE INDEX IF NOT EXISTS invoice_lines_invoice_id_idx ON invoice_lines (invoice_id);
CREATE INDEX IF NOT EXISTS invoice_lines_location_id_idx ON invoice_lines (location_id);

CREATE TABLE IF NOT EXISTS working_capital_positions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  as_of date NOT NULL,
  receivable_minor bigint NOT NULL,
  subcontractor_payable_minor bigint NOT NULL,
  parts_payable_minor bigint NOT NULL,
  currency text NOT NULL REFERENCES currencies(code),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS working_capital_positions_region_id_idx ON working_capital_positions (region_id);
CREATE INDEX IF NOT EXISTS working_capital_positions_as_of_idx ON working_capital_positions (as_of);

CREATE TABLE IF NOT EXISTS settlements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  firm_id uuid NOT NULL REFERENCES subcontractor_firms(id),
  period daterange NOT NULL,
  total_minor bigint NOT NULL,
  currency text NOT NULL REFERENCES currencies(code),
  state text NOT NULL DEFAULT 'draft' CHECK (state IN ('draft','issued','acknowledged','disputed','paid')),
  issued_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS settlements_region_id_idx ON settlements (region_id);
CREATE INDEX IF NOT EXISTS settlements_firm_id_idx ON settlements (firm_id);

CREATE TABLE IF NOT EXISTS settlement_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  settlement_id uuid NOT NULL REFERENCES settlements(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  rate_card_id uuid NOT NULL REFERENCES rate_cards(id),
  quantity_milli bigint NOT NULL,
  amount_minor bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS settlement_lines_region_id_idx ON settlement_lines (region_id);
CREATE INDEX IF NOT EXISTS settlement_lines_settlement_id_idx ON settlement_lines (settlement_id);
CREATE INDEX IF NOT EXISTS settlement_lines_job_id_idx ON settlement_lines (job_id);

CREATE TABLE IF NOT EXISTS sync_mutations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  device_id uuid NOT NULL REFERENCES devices(id),
  mutation_id text NOT NULL,
  device_seq bigint NOT NULL,
  entity_table text NOT NULL,
  entity_id uuid NOT NULL,
  op text NOT NULL CHECK (op IN ('insert','update','transition')),
  payload jsonb NOT NULL,
  client_observed_version integer,
  outcome text NOT NULL CHECK (outcome IN ('applied','duplicate','superseded','queued_for_human','rejected')),
  note text,
  device_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (device_id, mutation_id)
);
CREATE INDEX IF NOT EXISTS sync_mutations_region_id_idx ON sync_mutations (region_id);
CREATE INDEX IF NOT EXISTS sync_mutations_device_id_device_seq_idx ON sync_mutations (device_id, device_seq);
CREATE INDEX IF NOT EXISTS sync_mutations_entity_table_entity_id_idx ON sync_mutations (entity_table, entity_id);

CREATE TABLE IF NOT EXISTS sync_conflicts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  mutation_id uuid NOT NULL REFERENCES sync_mutations(id),
  entity_table text NOT NULL,
  entity_id uuid NOT NULL,
  server_state jsonb NOT NULL,
  device_intent jsonb NOT NULL,
  note text NOT NULL,
  resolved_by uuid,
  resolved_at timestamptz,
  resolution text CHECK (resolution IN ('accept_device','keep_server','manual')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS sync_conflicts_region_id_idx ON sync_conflicts (region_id);
CREATE INDEX IF NOT EXISTS sync_conflicts_resolved_at_idx ON sync_conflicts (resolved_at);
CREATE INDEX IF NOT EXISTS sync_conflicts_entity_table_entity_id_idx ON sync_conflicts (entity_table, entity_id);

CREATE TABLE IF NOT EXISTS audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  event_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  surface_id text NOT NULL,
  session_id uuid,
  request_id text,
  action text NOT NULL,
  entity text NOT NULL,
  entity_id uuid NOT NULL,
  before jsonb,
  after jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (event_id)
);
CREATE INDEX IF NOT EXISTS audit_log_region_id_idx ON audit_log (region_id);
CREATE INDEX IF NOT EXISTS audit_log_entity_entity_id_idx ON audit_log (entity, entity_id);
CREATE INDEX IF NOT EXISTS audit_log_occurred_at_idx ON audit_log (occurred_at);
CREATE INDEX IF NOT EXISTS audit_log_actor_id_idx ON audit_log (actor_id);

CREATE TABLE IF NOT EXISTS outbox (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  event_id uuid NOT NULL,
  topic text NOT NULL,
  entity text NOT NULL,
  entity_id uuid NOT NULL,
  payload jsonb NOT NULL,
  actor_id uuid NOT NULL,
  surface_id text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  attempts integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (event_id)
);
CREATE INDEX IF NOT EXISTS outbox_region_id_idx ON outbox (region_id);
CREATE INDEX IF NOT EXISTS outbox_published_at_occurred_at_idx ON outbox (published_at, occurred_at);
CREATE INDEX IF NOT EXISTS outbox_topic_idx ON outbox (topic);

CREATE TABLE IF NOT EXISTS subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  subscriber text NOT NULL,
  topic text NOT NULL,
  last_event_id uuid,
  last_occurred_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (subscriber, topic, region_id)
);
CREATE INDEX IF NOT EXISTS subscriptions_region_id_idx ON subscriptions (region_id);

CREATE TABLE IF NOT EXISTS storage_objects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  storage_key text NOT NULL,
  content_type text NOT NULL,
  byte_size bigint NOT NULL,
  sha256 bytea NOT NULL,
  uploaded_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (storage_key)
);
CREATE INDEX IF NOT EXISTS storage_objects_region_id_idx ON storage_objects (region_id);
CREATE INDEX IF NOT EXISTS storage_objects_storage_key_idx ON storage_objects (storage_key);

CREATE TABLE IF NOT EXISTS brand_themes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  host text NOT NULL,
  accent text NOT NULL,
  overrides jsonb NOT NULL,
  accent_admission jsonb NOT NULL,
  authored_by uuid NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (host),
  UNIQUE (org_id)
);
CREATE INDEX IF NOT EXISTS brand_themes_region_id_idx ON brand_themes (region_id);
CREATE INDEX IF NOT EXISTS brand_themes_host_idx ON brand_themes (host);

CREATE TABLE IF NOT EXISTS sla_timers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  response_term text NOT NULL,
  opened_at timestamptz NOT NULL,
  due_at timestamptz NOT NULL,
  satisfied_at timestamptz,
  breached_at timestamptz,
  escalation_stage integer NOT NULL DEFAULT 0 CHECK (escalation_stage BETWEEN 0 AND 3),
  shadow_mode boolean NOT NULL DEFAULT true,
  resolution_trace jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (job_id)
);
CREATE INDEX IF NOT EXISTS sla_timers_region_id_idx ON sla_timers (region_id);
CREATE INDEX IF NOT EXISTS sla_timers_job_id_idx ON sla_timers (job_id);
CREATE INDEX IF NOT EXISTS sla_timers_due_at_idx ON sla_timers (due_at);

-- The designed home for pre-account rows. A real organization and a real
-- region, so region_id never needs to be nullable and the shard key stays total.
INSERT INTO organizations (id, name, kind) VALUES
  ('00000000-0000-0000-0000-000000000001', 'PROSPECT', 'prospect'),
  ('00000000-0000-0000-0000-000000000003', 'AC Services (internal)', 'internal')
ON CONFLICT (id) DO NOTHING;

INSERT INTO regions (id, code, name, min_crew_density, active) VALUES
  ('00000000-0000-0000-0000-000000000002', 'UNASSIGNED', 'Unassigned (pre-account)', 0, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO currencies (code, minor_units) VALUES ('USD', 2) ON CONFLICT DO NOTHING;
