-- GENERATED by tools/ci/emit-schema.ts — do not edit by hand.
-- Source of truth: packages/schema/src/tables/*.ts
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS currencies (
  code text NOT NULL,
  minor_units integer NOT NULL,
  PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (version)
);

-- Tenant roots. PROSPECT is a real row here, which is why pre-account leads need no nullable column.
CREATE TABLE IF NOT EXISTS organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('internal','customer','subcontractor','vendor','prospect')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

-- The shard boundary itself.
CREATE TABLE IF NOT EXISTS regions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  min_crew_density integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  parent_id uuid REFERENCES accounts(id),
  tier text NOT NULL CHECK (tier IN ('parent','region','location','asset')),
  name text NOT NULL,
  external_ref text,
  address jsonb,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS accounts_region_id_idx ON accounts (region_id);
CREATE INDEX IF NOT EXISTS accounts_parent_id_idx ON accounts (parent_id);
CREATE INDEX IF NOT EXISTS accounts_tier_idx ON accounts (tier);

CREATE TABLE IF NOT EXISTS subcontractor_firms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  legal_name text NOT NULL,
  status text NOT NULL CHECK (status IN ('onboarding','active','suspended','terminated')),
  settlement_terms_days integer NOT NULL,
  diagnostic_data_rights_reserved boolean NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS subcontractor_firms_region_id_idx ON subcontractor_firms (region_id);

CREATE TABLE IF NOT EXISTS crews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  label text NOT NULL,
  employment_type text NOT NULL CHECK (employment_type IN ('employed','subcontracted')),
  firm_id uuid REFERENCES subcontractor_firms(id),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS crews_region_id_idx ON crews (region_id);
CREATE INDEX IF NOT EXISTS crews_firm_id_idx ON crews (firm_id);

CREATE TABLE IF NOT EXISTS crew_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  crew_id uuid NOT NULL REFERENCES crews(id),
  kind text NOT NULL CHECK (kind IN ('insurance','license','certification','background_check')),
  identifier text NOT NULL,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  document_key text,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS crew_credentials_region_id_idx ON crew_credentials (region_id);
CREATE INDEX IF NOT EXISTS crew_credentials_crew_id_valid_to_idx ON crew_credentials (crew_id, valid_to);

CREATE TABLE IF NOT EXISTS rate_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  firm_id uuid NOT NULL REFERENCES subcontractor_firms(id),
  service_code text NOT NULL,
  rate_minor bigint NOT NULL,
  currency text NOT NULL REFERENCES currencies(code),
  effective_from date NOT NULL,
  effective_to date,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS rate_cards_region_id_idx ON rate_cards (region_id);
CREATE INDEX IF NOT EXISTS rate_cards_firm_id_service_code_idx ON rate_cards (firm_id, service_code);

CREATE TABLE IF NOT EXISTS contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  account_id uuid NOT NULL REFERENCES accounts(id),
  billing_path text NOT NULL CHECK (billing_path IN ('one_time','residential_membership','enterprise_sla','project')),
  effective_from date NOT NULL,
  effective_to date,
  diagnostic_data_rights_reserved boolean NOT NULL,
  payment_terms_days integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS contracts_region_id_idx ON contracts (region_id);
CREATE INDEX IF NOT EXISTS contracts_account_id_idx ON contracts (account_id);

CREATE TABLE IF NOT EXISTS contract_term_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  contract_id uuid NOT NULL REFERENCES contracts(id),
  scope_tier text NOT NULL CHECK (scope_tier IN ('parent','region','location','asset')),
  scope_id uuid NOT NULL REFERENCES accounts(id),
  term_key text NOT NULL,
  term_value jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS contract_term_overrides_region_id_idx ON contract_term_overrides (region_id);
CREATE INDEX IF NOT EXISTS contract_term_overrides_contract_id_term_key_idx ON contract_term_overrides (contract_id, term_key);
CREATE INDEX IF NOT EXISTS contract_term_overrides_scope_id_idx ON contract_term_overrides (scope_id);

CREATE TABLE IF NOT EXISTS leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  source text NOT NULL,
  contact jsonb NOT NULL,
  requested_metro text,
  converted_account_id uuid REFERENCES accounts(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS leads_region_id_idx ON leads (region_id);
CREATE INDEX IF NOT EXISTS leads_converted_account_id_idx ON leads (converted_account_id);

CREATE TABLE IF NOT EXISTS call_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  lead_id uuid REFERENCES leads(id),
  direction text NOT NULL CHECK (direction IN ('inbound','outbound')),
  recording_key text,
  occurred_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS call_records_region_id_idx ON call_records (region_id);
CREATE INDEX IF NOT EXISTS call_records_lead_id_idx ON call_records (lead_id);

CREATE TABLE IF NOT EXISTS jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  account_id uuid NOT NULL REFERENCES accounts(id),
  contract_id uuid REFERENCES contracts(id),
  service_code text NOT NULL,
  window_start timestamptz NOT NULL,
  window_end timestamptz NOT NULL,
  sla_due_at timestamptz,
  state text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS jobs_region_id_idx ON jobs (region_id);
CREATE INDEX IF NOT EXISTS jobs_account_id_idx ON jobs (account_id);
CREATE INDEX IF NOT EXISTS jobs_state_window_start_idx ON jobs (state, window_start);

CREATE TABLE IF NOT EXISTS compliance_clearances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  crew_id uuid NOT NULL REFERENCES crews(id),
  window_start timestamptz NOT NULL,
  window_end timestamptz NOT NULL,
  credential_ids jsonb NOT NULL,
  evaluated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS compliance_clearances_region_id_idx ON compliance_clearances (region_id);
CREATE INDEX IF NOT EXISTS compliance_clearances_crew_id_window_end_idx ON compliance_clearances (crew_id, window_end);

CREATE TABLE IF NOT EXISTS assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  crew_id uuid NOT NULL REFERENCES crews(id),
  clearance_id uuid NOT NULL REFERENCES compliance_clearances(id),
  assigned_by uuid NOT NULL,
  released_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS assignments_region_id_idx ON assignments (region_id);
CREATE INDEX IF NOT EXISTS assignments_job_id_idx ON assignments (job_id);
CREATE INDEX IF NOT EXISTS assignments_crew_id_idx ON assignments (crew_id);

CREATE TABLE IF NOT EXISTS job_state_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  job_id uuid NOT NULL REFERENCES jobs(id),
  from_state text,
  to_state text NOT NULL,
  actor_id uuid NOT NULL,
  surface_id text NOT NULL,
  mutation_id text NOT NULL,
  occurred_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS job_state_events_region_id_idx ON job_state_events (region_id);
CREATE INDEX IF NOT EXISTS job_state_events_job_id_occurred_at_idx ON job_state_events (job_id, occurred_at);
CREATE INDEX IF NOT EXISTS job_state_events_job_id_mutation_id_idx ON job_state_events (job_id, mutation_id);

CREATE TABLE IF NOT EXISTS service_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  account_id uuid NOT NULL REFERENCES accounts(id),
  requested_by uuid NOT NULL,
  description text NOT NULL,
  job_id uuid REFERENCES jobs(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS service_requests_region_id_idx ON service_requests (region_id);
CREATE INDEX IF NOT EXISTS service_requests_account_id_idx ON service_requests (account_id);

CREATE TABLE IF NOT EXISTS invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  bill_to_account_id uuid NOT NULL REFERENCES accounts(id),
  billing_path text NOT NULL CHECK (billing_path IN ('one_time','residential_membership','enterprise_sla','project')),
  period_start date,
  period_end date,
  total_minor bigint NOT NULL,
  currency text NOT NULL REFERENCES currencies(code),
  issued_at timestamptz,
  due_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS invoices_region_id_idx ON invoices (region_id);
CREATE INDEX IF NOT EXISTS invoices_bill_to_account_id_idx ON invoices (bill_to_account_id);

CREATE TABLE IF NOT EXISTS invoice_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  invoice_id uuid NOT NULL REFERENCES invoices(id),
  account_id uuid NOT NULL REFERENCES accounts(id),
  job_id uuid REFERENCES jobs(id),
  description text NOT NULL,
  quantity_milli bigint NOT NULL,
  unit_price_minor bigint NOT NULL,
  amount_minor bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS invoice_lines_region_id_idx ON invoice_lines (region_id);
CREATE INDEX IF NOT EXISTS invoice_lines_invoice_id_idx ON invoice_lines (invoice_id);
CREATE INDEX IF NOT EXISTS invoice_lines_account_id_idx ON invoice_lines (account_id);

CREATE TABLE IF NOT EXISTS working_capital_positions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  as_of date NOT NULL,
  receivable_minor bigint NOT NULL,
  subcontractor_payable_minor bigint NOT NULL,
  parts_payable_minor bigint NOT NULL,
  currency text NOT NULL REFERENCES currencies(code),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS working_capital_positions_region_id_idx ON working_capital_positions (region_id);
CREATE INDEX IF NOT EXISTS working_capital_positions_as_of_idx ON working_capital_positions (as_of);

CREATE TABLE IF NOT EXISTS audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  actor_id uuid NOT NULL,
  surface_id text NOT NULL,
  action text NOT NULL,
  entity text NOT NULL,
  entity_id uuid NOT NULL,
  before jsonb,
  after jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS audit_log_region_id_idx ON audit_log (region_id);
CREATE INDEX IF NOT EXISTS audit_log_entity_entity_id_idx ON audit_log (entity, entity_id);
CREATE INDEX IF NOT EXISTS audit_log_occurred_at_idx ON audit_log (occurred_at);

CREATE TABLE IF NOT EXISTS outbox (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  topic text NOT NULL,
  payload jsonb NOT NULL,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS outbox_region_id_idx ON outbox (region_id);
CREATE INDEX IF NOT EXISTS outbox_published_at_idx ON outbox (published_at);

CREATE TABLE IF NOT EXISTS storage_objects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id),
  region_id uuid NOT NULL REFERENCES regions(id),
  storage_key text NOT NULL,
  content_type text NOT NULL,
  byte_size bigint NOT NULL,
  sha256 bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS storage_objects_region_id_idx ON storage_objects (region_id);
CREATE INDEX IF NOT EXISTS storage_objects_storage_key_idx ON storage_objects (storage_key);

-- The designed home for pre-account rows. A real organization and a real
-- region, so region_id never needs to be nullable and the shard key stays total.
INSERT INTO organizations (id, name, kind) VALUES
  ('00000000-0000-0000-0000-000000000010', 'PROSPECT', 'prospect')
ON CONFLICT (id) DO NOTHING;

INSERT INTO regions (id, code, name, min_crew_density, active) VALUES
  ('00000000-0000-0000-0000-000000000002', 'UNASSIGNED', 'Unassigned (pre-account)', 0, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO currencies (code, minor_units) VALUES ('USD', 2) ON CONFLICT DO NOTHING;
