import type { Tier } from "./tiers.ts";

/**
 * THE TERM POLICY REGISTER — D2 part two.
 *
 * The master plan's sentence "terms flow downward and may be overridden at any
 * level" is five rules wearing one coat (claude/07_D2_Hierarchy_Findings.md).
 * A resolver built to that sentence returns confidently wrong answers with a
 * clean trace: a location sets its own payment terms and the consolidated
 * invoice becomes unpayable; a location relaxes an SLA we carry the whole
 * exposure on; a site inherits the vendor warranty attached to the site next
 * door.
 *
 * So a term carries a POLICY, not just a value, and the policy is two
 * orthogonal axes — not four enum values, because an enum bundles independent
 * properties and the fifth case needs a fifth branch in every consumer:
 *
 *   authoring   which tiers may hold an override row for this term
 *   combine     how competing values resolve down the path
 *                 nearest   most specific tier wins
 *                 ratchet   an override may only TIGHTEN, direction declared
 *                 attach    binds to exactly one node and never walks
 *
 * What is NOT an axis: what happens on violation. It is always RAISE, on every
 * term, in every direction. Making it configurable is how an override flag
 * re-enters the system wearing a different name.
 *
 * THIS REGISTER IS CODE, NOT A TABLE. A table an ops user can edit is a table
 * someone edits at T-4 so tonight's invoice runs. It IS mirrored into the
 * database (`term_registry`, generated by tools/ci/emit-schema.ts, SELECT-only
 * for every runtime role) so that the admission trigger in migrations/0002 can
 * refuse an illegal override row from a psql session — but the mirror is
 * regenerated from here, never edited.
 *
 * Asymmetry to know before signing contracts: adding a term is cheap. Changing
 * a term's policy after override rows exist is not — every row written under
 * the old policy has to be re-admitted, and the ones that fail are terms a
 * customer currently believes they have.
 */

export type Combine =
  | { readonly kind: "nearest" }
  | { readonly kind: "ratchet"; readonly stricter: "lower" | "higher" }
  | { readonly kind: "attach" };

export type ValueKind = "int" | "money" | "text" | "enum" | "bool";

export type TermPolicy = {
  readonly key: string;
  readonly authoring: readonly Tier[];
  readonly combine: Combine;
  readonly valueKind: ValueKind;
  /** Allowed values when valueKind is "enum". Order is the ordinal used by ratchet: index 0 is LOWEST. */
  readonly values?: readonly string[];
  /** Why this term has this policy — the failure it prevents. Read by the S2 refusal message. */
  readonly rationale: string;
  /** Default when nothing on the path sets it. `undefined` means resolution raises. */
  readonly fallback?: unknown;
};

const ALL: readonly Tier[] = ["parent", "region", "location", "site"];

export const TERMS: Readonly<Record<string, TermPolicy>> = Object.freeze({
  // ---- money and billing: parent-only, because the consolidated invoice is one document
  payment_terms_days: {
    key: "payment_terms_days", authoring: ["parent"], combine: { kind: "nearest" }, valueKind: "int",
    rationale: "Amped centralises AP at the parent. Per-location payment terms make one consolidated invoice unpayable (non-negotiable #7).",
  },
  billing_rollup_tier: {
    key: "billing_rollup_tier", authoring: ["parent"], combine: { kind: "nearest" }, valueKind: "enum",
    values: ["site", "location", "region", "parent"],
    rationale: "Where the invoice header bills to. One answer per parent, or the detail sheets do not sum to anything.",
    fallback: "parent",
  },
  invoice_delivery: {
    key: "invoice_delivery", authoring: ["parent", "region"], combine: { kind: "nearest" }, valueKind: "enum",
    values: ["portal", "email", "edi"],
    rationale: "A region may have its own AP contact; a location may not.", fallback: "portal",
  },
  // ---- SLA: ratchet, because under Model A we carry the whole exposure
  sla_response: {
    key: "sla_response", authoring: ALL, combine: { kind: "ratchet", stricter: "lower" }, valueKind: "enum",
    // Ordinal, tightest first. Index is the rank; "stricter: lower" means an override may only move DOWN this list.
    values: ["1_hour", "2_hour", "4_hour", "same_day", "next_day", "48_hour"],
    rationale: "San Jose tightening same-day to 4-hour is correct. Reno relaxing to 48-hour is an obligation the parent MSA priced and we absorb with nothing to push outward.",
  },
  sla_credit_pct: {
    key: "sla_credit_pct", authoring: ["parent", "region", "location"], combine: { kind: "ratchet", stricter: "lower" }, valueKind: "int",
    rationale: "A location may negotiate a smaller credit, never a larger one than the MSA carries.",
  },
  pm_visits_per_year: {
    key: "pm_visits_per_year", authoring: ALL, combine: { kind: "ratchet", stricter: "higher" }, valueKind: "int",
    rationale: "More preventive visits is stricter. A site may buy more; it may not quietly buy fewer.",
  },
  // ---- pricing: nearest, any tier
  after_hours_multiplier_milli: {
    key: "after_hours_multiplier_milli", authoring: ALL, combine: { kind: "nearest" }, valueKind: "int",
    rationale: "Integer thousandths (1500 = 1.5x). Time-bounded rows so a February job reprices against the February contract.",
    fallback: 1500,
  },
  labor_rate_minor: {
    key: "labor_rate_minor", authoring: ALL, combine: { kind: "nearest" }, valueKind: "money",
    rationale: "Minor units as a STRING in jsonb — a JSON number is a double.",
  },
  // ---- vendor axis: attach, never walks
  vendor_warranty: {
    key: "vendor_warranty", authoring: ["site"], combine: { kind: "attach" }, valueKind: "text",
    rationale: "Boulder's roof units carry a Carrier 58-month parts warranty; the basement AHU twenty feet away does not. Authority comes from a vendor tree, not from the customer tree above the node.",
  },
  equipment_service_window: {
    key: "equipment_service_window", authoring: ["site"], combine: { kind: "attach" }, valueKind: "text",
    rationale: "Access constraints are physical facts about one site.",
  },
  // ---- data rights: parent-only, no fallback — a contract must state its position (OQ5)
  diagnostic_data_rights_reserved: {
    key: "diagnostic_data_rights_reserved", authoring: ["parent"], combine: { kind: "nearest" }, valueKind: "bool",
    rationale: "OQ5. Every agreement signed without the reservation is one that has to be renegotiated before Phase 4 licensing. No default, on purpose.",
  },
});

export const TERM_KEYS = Object.freeze(Object.keys(TERMS)) as readonly string[];

export class UnknownTermError extends Error {
  constructor(key: string) {
    super(`[terms] "${key}" is not in the term policy register. A term with no entry raises rather than defaulting to cascade — add it to packages/contracts/src/terms.ts in a reviewed diff, stating its authoring tiers and combine rule.`);
    this.name = "UnknownTermError";
  }
}

export const termPolicy = (key: string): TermPolicy => {
  const p = TERMS[key];
  if (!p) throw new UnknownTermError(key);
  return p;
};

/** Ordinal rank used by ratchet. Ints compare numerically; enums by declared order. */
export const termRank = (p: TermPolicy, value: unknown): number => {
  if (p.valueKind === "enum") {
    const i = (p.values ?? []).indexOf(String(value));
    if (i < 0) throw new Error(`[terms] "${value}" is not a legal value for ${p.key}; legal: ${(p.values ?? []).join(", ")}`);
    return i;
  }
  if (p.valueKind === "int") {
    if (typeof value !== "number" || !Number.isInteger(value)) throw new Error(`[terms] ${p.key} must be an integer, got ${JSON.stringify(value)}`);
    return value;
  }
  throw new Error(`[terms] ${p.key} is ${p.valueKind}; ratchet needs an ordinal`);
};

/** Shape check for a value against its term. Throws with the reason; never coerces. */
export const checkTermValue = (p: TermPolicy, value: unknown): void => {
  switch (p.valueKind) {
    case "int":
      if (typeof value !== "number" || !Number.isInteger(value)) throw new Error(`[terms] ${p.key} must be an integer`);
      return;
    case "bool":
      if (typeof value !== "boolean") throw new Error(`[terms] ${p.key} must be true or false`);
      return;
    case "text":
      if (typeof value !== "string" || value.length === 0) throw new Error(`[terms] ${p.key} must be non-empty text`);
      return;
    case "enum":
      termRank(p, value);
      return;
    case "money":
      // Money crosses the jsonb boundary as a string of minor units. A JSON number is IEEE754.
      if (typeof value !== "string" || !/^-?\d+$/.test(value)) throw new Error(`[terms] ${p.key} is money: a string of integer minor units, not a number`);
      return;
  }
};
