-- GENERATED by tools/ci/emit-schema.ts — do not edit by hand. Applied on EVERY migrate run.
-- Source of truth: packages/contracts/src/terms.ts
INSERT INTO term_registry (key, authoring_tiers, combine_kind, stricter, value_kind, enum_values) VALUES
  ('payment_terms_days', '["parent"]'::jsonb, 'nearest', NULL, 'int', NULL),
  ('billing_rollup_tier', '["parent"]'::jsonb, 'nearest', NULL, 'enum', '["site","location","region","parent"]'::jsonb),
  ('invoice_delivery', '["parent","region"]'::jsonb, 'nearest', NULL, 'enum', '["portal","email","edi"]'::jsonb),
  ('sla_response', '["parent","region","location","site"]'::jsonb, 'ratchet', 'lower', 'enum', '["1_hour","2_hour","4_hour","same_day","next_day","48_hour"]'::jsonb),
  ('sla_credit_pct', '["parent","region","location"]'::jsonb, 'ratchet', 'lower', 'int', NULL),
  ('pm_visits_per_year', '["parent","region","location","site"]'::jsonb, 'ratchet', 'higher', 'int', NULL),
  ('after_hours_multiplier_milli', '["parent","region","location","site"]'::jsonb, 'nearest', NULL, 'int', NULL),
  ('labor_rate_minor', '["parent","region","location","site"]'::jsonb, 'nearest', NULL, 'money', NULL),
  ('vendor_warranty', '["site"]'::jsonb, 'attach', NULL, 'text', NULL),
  ('equipment_service_window', '["site"]'::jsonb, 'attach', NULL, 'text', NULL),
  ('diagnostic_data_rights_reserved', '["parent"]'::jsonb, 'nearest', NULL, 'bool', NULL)
ON CONFLICT (key) DO UPDATE SET
  authoring_tiers = EXCLUDED.authoring_tiers,
  combine_kind    = EXCLUDED.combine_kind,
  stricter        = EXCLUDED.stricter,
  value_kind      = EXCLUDED.value_kind,
  enum_values     = EXCLUDED.enum_values;
DELETE FROM term_registry WHERE key NOT IN ('payment_terms_days', 'billing_rollup_tier', 'invoice_delivery', 'sla_response', 'sla_credit_pct', 'pm_visits_per_year', 'after_hours_multiplier_milli', 'labor_rate_minor', 'vendor_warranty', 'equipment_service_window', 'diagnostic_data_rights_reserved');
