#!/usr/bin/env node
/**
 * Generates each surface app's boot file, README and FRAME from the registry,
 * plus docs/SURFACES.md.
 *
 *   node tools/ci/emit-surfaces.ts          write everything
 *   node tools/ci/emit-surfaces.ts --check  exit 1 if any emitted file differs (what the guard runs)
 *
 * Generated on purpose: a hand-written README describing a surface's write
 * allowlist is a second source of truth, and the second source of truth is
 * always the one people read and never the one that is enforced.
 *
 * The frame (09 §3.3) is rendered HERE, at build time, not per request by a
 * server: density class, the token CSS as `:root` variables, the degraded slot
 * carrying the registry's declared text, the mount point, the bundle tag. There
 * is no surface-side server process to run, monitor, or turn into a second
 * access path. Zero-install: node: imports and relative .ts imports only, and
 * deterministic output, so the frame is byte-comparable.
 */
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { SURFACES, SURFACE_IDS, type Surface } from "../../packages/contracts/src/index.ts";
import { DENSITY, tokenCss } from "../../packages/tokens/src/index.ts";

const ROOT = fileURLToPath(new URL("../../", import.meta.url));

const escapeHtml = (s: string): string =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export const renderPackageJson = (s: Surface): string => JSON.stringify({
  name: `@ac/${s.app}`, version: "0.0.0", private: true, type: "module",
  main: "./src/main.ts",
  dependencies: { "@ac/shell": "workspace:*", "@ac/ui": "workspace:*", "@ac/contracts": "workspace:*" },
}, null, 2) + "\n";

export const renderMain = (s: Surface): string => `import { createShell, connectShell, type ConnectConfig } from "../../../packages/shell/src/index.ts";
import { SURFACES } from "../../../packages/contracts/src/index.ts";
import type { Principal } from "../../../packages/contracts/src/index.ts";

/**
 * ${s.id} — ${s.name}
 *
 * Block ${s.block} · Phase ${s.phase} · ${s.density} density · ${s.enabled ? "enabled" : "NOT ENABLED (phase gate)"}
 *
 * Auth: ${s.authScope}
 * Writes: ${s.writes.length ? s.writes.join(", ") : "NOTHING — read-only by construction"}
 *
 * Degraded mode:
 *   ${s.degraded}
 *
 * This surface owns no data. Every read and every write goes through
 * \`shell.gateway\` — the client generated from the operation catalogue — and
 * nothing else. It cannot resolve a database driver (.npmrc isolation,
 * ac/no-db-in-surface, tools/ci/schema-guard.ts) and it cannot call fetch
 * (ac/no-fetch-in-surface, the same guard). A request that is not in
 * packages/contracts/src/operations.ts has no method here.
 */
export const SURFACE = SURFACES.${s.id};

/** Configuration-only shell — the registry checks, no transport. */
export const boot = (principal: Principal) => createShell({ surfaceId: "${s.id}", principal });

/** Live shell — login, hierarchy context, generated client, event stream, degraded flag. */
export const connect = (cfg: Omit<ConnectConfig, "surfaceId">) => connectShell({ ...cfg, surfaceId: "${s.id}" });
`;

/**
 * The frame. One file per surface, identical in shape across all eight; what
 * differs is data from the registry. `./ui.css` and `./bundle.js` are what
 * tools/ci/build-surface.ts writes beside it in dist/.
 *
 * The degraded slot carries the declared text in the HTML itself, so the
 * outage banner does not depend on the bundle having loaded — the bundle only
 * flips `hidden` and appends the age (packages/ui applyDegraded).
 */
export const renderFrame = (s: Surface): string => `<!doctype html>
<!-- GENERATED from packages/contracts/src/surfaces.ts by tools/ci/emit-surfaces.ts. Do not edit. -->
<html lang="en" data-surface="${s.id}" data-density="${s.density}"${s.enabled ? "" : ` data-enabled="false"`}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="referrer" content="same-origin">
<title>${escapeHtml(s.name)}</title>
<style>${tokenCss(s.density)}</style>
<link rel="stylesheet" href="./ui.css">
</head>
<body>
<ac-degraded hidden role="alert" data-density="${s.density}">${escapeHtml(s.degraded)}</ac-degraded>
<main id="mount"></main>
<script type="module" src="./bundle.js"></script>
</body>
</html>
`;

export const renderReadme = (s: Surface): string => {
  const d = DENSITY[s.density];
  return `# ${s.id} — ${s.name}

> GENERATED from \`packages/contracts/src/surfaces.ts\`. Edit the registry, run
> \`node tools/ci/emit-surfaces.ts\`. Do not edit this file.

| | |
|---|---|
| Block | ${s.block} |
| Phase | ${s.phase}${s.enabled ? "" : " — not enabled"} |
| Namespace | \`${s.namespace}\` |
| Auth scope | ${s.authScope} |
| Scope binding | \`${s.scopeBinding}\` |
| Density | \`${s.density}\` — ${d.controlHeight} controls, ${d.bodyText} body, ${d.hoverAffordances ? "hover affordances allowed" : "NO hover-dependent affordances"} |
| Realtime | ${s.realtime ? "hard requirement" : "no"} |
| Offline writes | ${s.offline ? "yes — device holds intent, server holds truth" : "no"} |

## Writes

${s.writes.length ? s.writes.map((w) => `- \`${w}\``).join("\n") : "**Nothing.** The write allowlist is empty in the registry, and the gateway unit of work checks it on every mutation. This is not a convention anyone has to remember."}

## Degraded mode

${s.degraded}

## Runtime

\`frame.html\` is emitted from the registry (density, tokens as CSS variables,
the degraded slot, the mount point). \`node tools/ci/build-surface.ts ${s.id}\`
bundles \`src/main.ts\` with esbuild into \`dist/\` beside the frame and the
component stylesheet. Screens are declared in \`src/screens.ts\` and may use
only operations the catalogue admits for ${s.id}; the guard checks it.

## What this surface must never do

- Own data, or hold a database credential.
- Write an entity outside the list above — \`SurfaceWriteDenied\` on any attempt.
- Filter scope client-side. Scoping is enforced at the gateway or it is not enforced.
- Import the renderer. A surface imports \`@ac/ui\`; preact lives behind it.
`;
};

export const renderSurfacesDoc = (): string => {
  const rows = SURFACE_IDS.map((id) => {
    const s = SURFACES[id];
    return `| ${s.id} | ${s.name} | ${s.block} | ${s.phase} | \`${s.density}\` | ${s.authScope} | ${s.writes.length ? s.writes.map((w) => `\`${w}\``).join(", ") : "—"} |`;
  }).join("\n");
  return `# The eight surfaces

> GENERATED from \`packages/contracts/src/surfaces.ts\`.

Every screen in the platform is one of eight websites. None owns data. Each is a
scoped view onto the same multi-tenant hierarchy, reached only through the API
gateway.

| ID | Surface | Block | Phase | Density | Auth scope | Writes |
|----|---------|-------|-------|---------|-----------|--------|
${rows}

## Build order

1. Backbone contract — schema with \`region_id\` everywhere, gateway, auth with tier claims, event stream, audit log
2. **S0** — the shared shell: operation catalogue → generated client → shell transport (login, hierarchy context, SSE, refusal mapping, degraded flag). Every surface below boots through it
3. **S2** — hierarchy, contracts and the subcontractor registry must exist before anything dispatches against them
4. **S3 + S5 together** — the fallback is what lets the tablet ship without being a single point of failure
5. Yocto tablet — the long pole, de-risked because S5 already carries the field
6. **S6** — required for Amped end-to-end in Phase 1; tier scoping is the acceptance test
7. **S8** — D12 minimum cut: compliance intake + settlement visibility
8. **S1** — off the critical path, ship whenever a hand is free
9. **S4** (Phase 2), **S7** (Phase 4)

## Runtime (09)

Each surface is a build-rendered \`frame.html\` (from this registry) plus one
esbuild bundle of \`src/main.ts\`, served as static files. Preact/htm/signals
live in \`packages/ui\` alone; a surface imports \`@ac/ui\`. Screens are a
registry (\`src/screens.ts\`) checked against the operation catalogue.
`;
};

export type Emitted = { readonly path: string; readonly content: string };

/** Every file the emitter owns, as (repo-relative path, content). The guard and --check compare these. */
export const emitted = (): readonly Emitted[] => {
  const out: Emitted[] = [];
  for (const id of SURFACE_IDS) {
    const s = SURFACES[id];
    const dir = join("apps", s.app);
    out.push({ path: join(dir, "package.json"), content: renderPackageJson(s) });
    out.push({ path: join(dir, "src/main.ts"), content: renderMain(s) });
    out.push({ path: join(dir, "frame.html"), content: renderFrame(s) });
    out.push({ path: join(dir, "README.md"), content: renderReadme(s) });
  }
  out.push({ path: "docs/SURFACES.md", content: renderSurfacesDoc() });
  return out;
};

/** Paths whose committed content differs from what the registry emits today. */
export const drifted = (): readonly string[] =>
  emitted().filter((e) => {
    const p = join(ROOT, e.path);
    return !existsSync(p) || readFileSync(p, "utf8") !== e.content;
  }).map((e) => e.path);

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  if (process.argv.includes("--check")) {
    const d = drifted();
    if (d.length) {
      console.error(`emit-surfaces: ${d.length} file(s) have drifted from the registry — run \`node tools/ci/emit-surfaces.ts\` and commit:\n  ${d.join("\n  ")}`);
      process.exit(1);
    }
    console.log(`emit-surfaces: ${emitted().length} emitted files are current`);
  } else {
    for (const e of emitted()) {
      const p = join(ROOT, e.path);
      mkdirSync(join(p, ".."), { recursive: true });
      writeFileSync(p, e.content);
    }
    console.log(`emitted ${SURFACE_IDS.length} surface apps (package.json, src/main.ts, frame.html, README.md) + ${relative(ROOT, join(ROOT, "docs/SURFACES.md"))}`);
  }
}
