#!/usr/bin/env node
/**
 * Generates each surface app's boot file and README from the registry, plus
 * docs/SURFACES.md.
 *
 * Generated on purpose: a hand-written README describing a surface's write
 * allowlist is a second source of truth, and the second source of truth is
 * always the one people read and never the one that is enforced.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { SURFACES, SURFACE_IDS } from "../../packages/contracts/src/index.ts";
import { DENSITY } from "../../packages/tokens/src/density.ts";

const ROOT = fileURLToPath(new URL("../../", import.meta.url));

for (const id of SURFACE_IDS) {
  const s = SURFACES[id];
  const dir = join(ROOT, "apps", s.app);
  mkdirSync(join(dir, "src"), { recursive: true });

  writeFileSync(join(dir, "package.json"), JSON.stringify({
    name: `@ac/${s.app}`, version: "0.0.0", private: true, type: "module",
    main: "./src/main.ts",
    dependencies: { "@ac/shell": "workspace:*", "@ac/ui": "workspace:*", "@ac/contracts": "workspace:*" },
  }, null, 2) + "\n");

  writeFileSync(join(dir, "src/main.ts"), `import { createShell } from "../../../packages/shell/src/index.ts";
import { SURFACES } from "../../../packages/contracts/src/index.ts";
import type { Principal } from "../../../packages/contracts/src/index.ts";

/**
 * ${s.id} — ${s.name}
 *
 * Block ${s.block} · Phase ${s.phase} · ${s.density} density · ${s.enabled ? "enabled" : "NOT ENABLED (phase gate)"}
 *
 * Auth: ${s.authScope}
 * Writes: ${s.writes.length ? s.writes.join(", ") : "NOTHING — read-only by construction"}
 *
 * Degraded mode:
 *   ${s.degraded}
 *
 * This surface owns no data. Every read and every write goes through the shell
 * to the gateway. It cannot resolve a database driver: .npmrc isolation, then
 * ac/no-db-in-surface, then tools/ci/schema-guard.ts.
 */
export const SURFACE = SURFACES.${s.id};

export const boot = (principal: Principal) => createShell({ surfaceId: "${s.id}", principal });
`);

  const d = DENSITY[s.density];
  writeFileSync(join(dir, "README.md"), `# ${s.id} — ${s.name}

> GENERATED from \`packages/contracts/src/surfaces.ts\`. Edit the registry, run
> \`node tools/ci/emit-surfaces.ts\`. Do not edit this file.

| | |
|---|---|
| Block | ${s.block} |
| Phase | ${s.phase}${s.enabled ? "" : " — not enabled"} |
| Namespace | \`${s.namespace}\` |
| Auth scope | ${s.authScope} |
| Scope binding | \`${s.scopeBinding}\` |
| Density | \`${s.density}\` — ${d.controlHeight} controls, ${d.bodyText} body, ${d.hoverAffordances ? "hover affordances allowed" : "NO hover-dependent affordances"} |
| Realtime | ${s.realtime ? "hard requirement" : "no"} |
| Offline writes | ${s.offline ? "yes — device holds intent, server holds truth" : "no"} |

## Writes

${s.writes.length ? s.writes.map((w) => `- \`${w}\``).join("\n") : "**Nothing.** The write allowlist is empty in the registry, and the gateway unit of work checks it on every mutation. This is not a convention anyone has to remember."}

## Degraded mode

${s.degraded}

## What this surface must never do

- Own data, or hold a database credential.
- Write an entity outside the list above — \`SurfaceWriteDenied\` on any attempt.
- Filter scope client-side. Scoping is enforced at the gateway or it is not enforced.
`);
}

const rows = SURFACE_IDS.map((id) => {
  const s = SURFACES[id];
  return `| ${s.id} | ${s.name} | ${s.block} | ${s.phase} | \`${s.density}\` | ${s.authScope} | ${s.writes.length ? s.writes.map((w) => `\`${w}\``).join(", ") : "—"} |`;
}).join("\n");

writeFileSync(join(ROOT, "docs/SURFACES.md"), `# The eight surfaces

> GENERATED from \`packages/contracts/src/surfaces.ts\`.

Every screen in the platform is one of eight websites. None owns data. Each is a
scoped view onto the same multi-tenant hierarchy, reached only through the API
gateway.

| ID | Surface | Block | Phase | Density | Auth scope | Writes |
|----|---------|-------|-------|---------|-----------|--------|
${rows}

## Build order

1. Backbone contract — schema with \`region_id\` everywhere, gateway, auth with tier claims, event stream, audit log
2. **S2** — hierarchy, contracts and the subcontractor registry must exist before anything dispatches against them
3. **S3 + S5 together** — the fallback is what lets the tablet ship without being a single point of failure
4. Yocto tablet — the long pole, de-risked because S5 already carries the field
5. **S6** — required for Amped end-to-end in Phase 1; tier scoping is the acceptance test
6. **S8** — D12 minimum cut: compliance intake + settlement visibility
7. **S1** — off the critical path, ship whenever a hand is free
8. **S4** (Phase 2), **S7** (Phase 4)
`);

console.log(`emitted ${SURFACE_IDS.length} surface apps + docs/SURFACES.md`);
