#!/usr/bin/env node
/**
 * Generates packages/sdk/src/generated/client.ts from the operation catalogue.
 *
 *   node tools/ci/emit-sdk.ts          write the client
 *   node tools/ci/emit-sdk.ts --check  exit 1 if the committed client differs
 *
 * The generated client is the ONLY thing a surface calls to reach the gateway.
 * Generating it from the same constant the gateway builds its route table from
 * is what makes "the client's methods and the gateway's routes are the same
 * list" a fact the guard checks rather than a sentence a reviewer believes.
 *
 * Zero-install: node: imports only, relative .ts imports, deterministic output
 * (sorted by operation id; no timestamps).
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { OPERATIONS, OPERATION_IDS } from "../../packages/contracts/src/operations.ts";

const ROOT = fileURLToPath(new URL("../../", import.meta.url));
const OUT = join(ROOT, "packages/sdk/src/generated/client.ts");

export const render = (): string => {
  const ids = [...OPERATION_IDS].sort();
  const methods = ids.map((id) => {
    const op = OPERATIONS[id];
    const io = `OperationIO[${JSON.stringify(id)}]`;
    const doc = `  /** \`${op.method} ${op.path}\` · ${op.kind} · ${op.auth} · surfaces: ${op.surfaces.join(", ")}\n   *\n   * ${op.summary} */`;
    if (op.kind === "stream") {
      return `${doc}\n  ${op.sdkMethod}(onEvent: (e: EventEnvelope) => void, onState: (s: StreamState) => void = () => {}): () => void {\n    return transport.stream(OPERATIONS[${JSON.stringify(id)}], onEvent, onState);\n  },`;
    }
    if (op.carrier === "none") {
      return `${doc}\n  ${op.sdkMethod}(): Promise<${io}["output"]> {\n    return transport.request(OPERATIONS[${JSON.stringify(id)}], undefined) as Promise<${io}["output"]>;\n  },`;
    }
    return `${doc}\n  ${op.sdkMethod}(input: ${io}["input"]): Promise<${io}["output"]> {\n    return transport.request(OPERATIONS[${JSON.stringify(id)}], input) as Promise<${io}["output"]>;\n  },`;
  });

  return `// GENERATED by tools/ci/emit-sdk.ts from packages/contracts/src/operations.ts.
// Do not edit. Edit the catalogue and run \`npm run sdk:generate\`.
// tools/ci/schema-guard.ts fails the build if this file has drifted.
import { OPERATIONS, type OperationIO, type EventEnvelope } from "../../../contracts/src/index.ts";
import type { Transport, StreamState } from "../runtime.ts";

/**
 * One method per operation in the catalogue — ${ids.length} today. There is no
 * generic \`request(path)\`; a request the gateway did not agree to serve has
 * no method here.
 */
export const createGatewayClient = (transport: Transport) => ({
${methods.join("\n\n")}
});

export type GatewayClient = ReturnType<typeof createGatewayClient>;

/** Every sdkMethod in the catalogue, for the parity guard. */
export const GENERATED_METHODS = Object.freeze([${ids.map((id) => JSON.stringify(OPERATIONS[id].sdkMethod)).join(", ")}] as const);
`;
};

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const next = render();
  if (process.argv.includes("--check")) {
    const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
    if (current !== next) {
      console.error(`emit-sdk: ${OUT} has drifted from the catalogue — run \`npm run sdk:generate\` and commit`);
      process.exit(1);
    }
    console.log("emit-sdk: generated client is current");
  } else {
    mkdirSync(join(ROOT, "packages/sdk/src/generated"), { recursive: true });
    writeFileSync(OUT, next);
    console.log(`emit-sdk: wrote ${OUT} (${OPERATION_IDS.length} operations)`);
  }
}
