#!/usr/bin/env node
/**
 * Emits migrations/0001_bootstrap.sql from the table definitions and the term
 * policy register. The SQL is generated and committed so migration diffs are
 * reviewable — but it is never hand-edited. `node tools/ci/schema-guard.ts`
 * fails if it drifts.
 */
import { writeFileSync } from "node:fs";
import {
  ALL_TABLES, toDdl, PROSPECT_ORG_ID, UNASSIGNED_REGION_ID, INTERNAL_ORG_ID,
} from "../../packages/schema/src/index.ts";
import { TERMS } from "../../packages/contracts/src/terms.ts";

const header = `-- GENERATED by tools/ci/emit-schema.ts — do not edit by hand.
-- Source of truth: packages/schema/src/tables/*.ts and packages/contracts/src/terms.ts
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;
`;

const sqlLit = (s: string) => `'${s.replace(/'/g, "''")}'`;

const termRows = Object.values(TERMS).map((t) => {
  const stricter = t.combine.kind === "ratchet" ? sqlLit(t.combine.stricter) : "NULL";
  const enums = t.values ? `${sqlLit(JSON.stringify(t.values))}::jsonb` : "NULL";
  return `  (${sqlLit(t.key)}, ${sqlLit(JSON.stringify(t.authoring))}::jsonb, ${sqlLit(t.combine.kind)}, ${stricter}, ${sqlLit(t.valueKind)}, ${enums})`;
});

const seed = `
-- The designed home for pre-account rows. A real organization and a real
-- region, so region_id never needs to be nullable and the shard key stays total.
INSERT INTO organizations (id, name, kind) VALUES
  ('${PROSPECT_ORG_ID}', 'PROSPECT', 'prospect'),
  ('${INTERNAL_ORG_ID}', 'AC Services (internal)', 'internal')
ON CONFLICT (id) DO NOTHING;

INSERT INTO regions (id, code, name, min_crew_density, active) VALUES
  ('${UNASSIGNED_REGION_ID}', 'UNASSIGNED', 'Unassigned (pre-account)', 0, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO currencies (code, minor_units) VALUES ('USD', 2) ON CONFLICT DO NOTHING;
`;

/**
 * The term policy register, mirrored from packages/contracts/src/terms.ts.
 * REPEATABLE: migrate.ts applies it on every run, after the versioned
 * migrations, so the database mirror can never be older than the code. A key
 * removed from the code is removed here too — and the FK from
 * contract_term_overrides refuses if any override row still uses it, which is
 * the right answer: a term with signed rows cannot quietly disappear.
 */
const repeatable = `-- GENERATED by tools/ci/emit-schema.ts — do not edit by hand. Applied on EVERY migrate run.
-- Source of truth: packages/contracts/src/terms.ts
INSERT INTO term_registry (key, authoring_tiers, combine_kind, stricter, value_kind, enum_values) VALUES
${termRows.join(",\n")}
ON CONFLICT (key) DO UPDATE SET
  authoring_tiers = EXCLUDED.authoring_tiers,
  combine_kind    = EXCLUDED.combine_kind,
  stricter        = EXCLUDED.stricter,
  value_kind      = EXCLUDED.value_kind,
  enum_values     = EXCLUDED.enum_values;
DELETE FROM term_registry WHERE key NOT IN (${Object.keys(TERMS).map(sqlLit).join(", ")});
`;
writeFileSync(new URL("../../packages/schema/migrations/repeatable/R_term_registry.sql", import.meta.url), repeatable);

const body = ALL_TABLES.map((t) => {
  const c = t.comment ? `-- ${t.comment}\n` : "";
  return `${c}${toDdl(t)}`;
}).join("\n\n");

const out = new URL("../../packages/schema/migrations/0001_bootstrap.sql", import.meta.url);
writeFileSync(out, `${header}\n${body}\n${seed}`);
console.log(`wrote 0001_bootstrap.sql — ${ALL_TABLES.length} tables, ${termRows.length} terms`);
