#!/usr/bin/env node
/**
 * Emits migrations/0001_bootstrap.sql from the table definitions.
 * The SQL is generated and committed, so migration diffs are reviewable — but
 * it is never hand-edited. `pnpm guard:schema` fails if it drifts.
 */
import { writeFileSync } from "node:fs";
import { ALL_TABLES, toDdl, PROSPECT_ORG_ID, UNASSIGNED_REGION_ID } from "../../packages/schema/src/index.ts";

const header = `-- GENERATED by tools/ci/emit-schema.ts — do not edit by hand.
-- Source of truth: packages/schema/src/tables/*.ts
CREATE EXTENSION IF NOT EXISTS pgcrypto;
`;

const seed = `
-- The designed home for pre-account rows. A real organization and a real
-- region, so region_id never needs to be nullable and the shard key stays total.
INSERT INTO organizations (id, name, kind) VALUES
  ('${PROSPECT_ORG_ID}', 'PROSPECT', 'prospect')
ON CONFLICT (id) DO NOTHING;

INSERT INTO regions (id, code, name, min_crew_density, active) VALUES
  ('${UNASSIGNED_REGION_ID}', 'UNASSIGNED', 'Unassigned (pre-account)', 0, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO currencies (code, minor_units) VALUES ('USD', 2) ON CONFLICT DO NOTHING;
`;

const body = ALL_TABLES.map((t) => {
  const c = t.comment ? `-- ${t.comment}\n` : "";
  return `${c}${toDdl(t)}`;
}).join("\n\n");

const out = new URL("../../packages/schema/migrations/0001_bootstrap.sql", import.meta.url);
writeFileSync(out, `${header}\n${body}\n${seed}`);
console.log(`wrote 0001_bootstrap.sql — ${ALL_TABLES.length} tables`);
